# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d4722183b06758f2200b4ce58f435d6c2f9e59bdd76ad1359cc49eef3aa531afb7c6e8cd9af80925ddc1f59182bb3e2de5030674ba897c0208f58580dacf796

test:
  secret_key_base: 7d3cd3eca06a4151a07bd16a439a6f3b104c93efecbd5f731222a25b78bd446cbe0252425dcbb96605b2d1535fdefea3e4134ebf275d7c6a9500a3c8e55bbddb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
